name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Echo .NET version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore

    - name: Some Message
      run: echo "Will build and run tests."

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test ./Tests/*.csproj --verbosity quiet

  parallelJob:
     runs-on: ubuntu-latest
     needs: build
     steps:
  
      - name: Parallel Job Step 1
        run: echo "This is step 1 of the parallel job."

  dependantJob:
    needs: parallelJob
    runs-on: ubuntu-latest
    steps:

      - name: Dependant Job Step
        run: echo "This job runs after the parallel job is complete."