name: status check functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:

          - name: step 1
            run: sleep 20
            
          - name: runs on failure
            if: failure()
            run: echo 'Runs only on failure'

            #i know this isnt required
          - name: runs on success
            if: success()
            run: echo 'runs on success'

          - name: always runs
            #if: success() || failure()
            if: always()
            run: echo 'always runs'

          - name: runs on cancel
            if: cancelled()
            run: echo 'runs on cancel'

    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps: 
            - run: echo 'job 2'