name: secrets and variables
on: [push]

jobs:
    log-vars:
     runs-on: ubuntu-latest
     environment: Production
     env:
      MY_SECRET: ${{secrets.MY_SECRET}}
      BANANAS_QUANTITY: ${{vars.ENV_BANANAS_QUANTITY}}
      REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}
      REPOSITORY_VARIABLE: ${{vars.REPOSITORY_VARIABLE}}
      ACTIVATED: ${{vars.ACTIVATED}}
      
     steps:
        - name: run only if it is activated
          if: env.ACTIVATED == 'true'
          run: echo "i can run"
        - name: log vars
          run: |
           echo '${{env.BANANAS_QUANTITY}}'
           echo '${{env.MY_SECRET}}'
           echo '${{env.REPOSITORY_SECRET}}'
           echo '${{env.REPOSITORY_VARIABLE}}'
           echo '${{env.ACTIVATED}}'