name: Working Directories & shells
on: [push]
jobs:
    
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: display working directory & list files
              run: |
                    pwd
                    ls -a
                    echo $GITHUB_SHA #id of commit
                    echo $GITHUB_REPOSITORY
                    echo $GITHUB_WORKSPACE

    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: display working directory & list files
              run: |
                    Get-Location
                    Get-ChildItem -Force
                    echo $env:GITHUB_SHA  # id of commit
                    echo $env:GITHUB_REPOSITORY
                    echo $env:GITHUB_WORKSPACE